bench: 
    - tpca
graph:
    using_cmd: '18:($9/$8)'
    x_label: 'Zipf Coefficient'
    y_label: 'Commit Rate'
    y_range: '[0:]'
    x_range: '[0.5:1]'
    x_tics: 0,0.1
    output_file: 'multi_dc_${bench}_${txn}_zipf_commits_attempts'
    key_location: 'above'