bench: 
    - tpcc
graph:
    using_cmd: '($6):($9/$8)'
    x_label: 'Clients'
    y_label: 'Commit Rate'
    log_scale: x 10
    output_file: 'single_dc_${bench}_${txn}_client_commits_attempts'
    key_location: 'above'
    y_range: '[0:]'
    x_range: '[1:4000]'
