sudo: required
language: cpp
compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    - boost-latest
      #    - kubuntu-backports
    packages:
    - build-essential
    - g++-4.9
    - gcc-4.9
    - clang-3.8
    - libboost1.55-all-dev
    - python-dev
    - python-pip
before_install:
#    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
#    - sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
#    - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
    - sudo add-apt-repository -y ppa:smfengler/ppa
    - sudo add-apt-repository -y ppa:chris-lea/protobuf
    - sudo add-apt-repository -y ppa:chris-lea/zeromq
    - sudo apt-get update -qq
    - sudo apt-get install -y libyaml-cpp-dev
    - sudo apt-get install -y protobuf-compiler
    - sudo apt-get install -y libprotobuf-dev
    - sudo apt-get install -y libzmq3-dev
#    - sudo apt-get install -y build-essential
#    - sudo apt-get install -y g++-4.9 gcc-4.9
#    - sudo apt-get install -y clang-3.8
#    - sudo apt-get install -y libapr1-dev libaprutil1-dev  
#    - sudo apt-get install -y libboost-dev 
#    - sudo apt-get install -y python-dev
#    - sudo apt-get install -y python-pip 
    - pip install --user tabulate 
    - export CXX="g++-4.9" CC="gcc-4.9"
script:
    - ./waf configure
    - ./waf -j 1

