#!/bin/bash
set -x
# Fig4
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 1 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 42G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 1 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 42G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 1 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 42G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 4 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 48G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 4 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 48G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 4 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 48G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 8 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 56G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 8 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 56G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 8 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 56G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 12 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 64G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 12 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 64G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 12 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 64G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 16 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 72G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 16 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 72G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 16 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 72G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 20 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 80G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 20 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 80G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 20 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 80G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 24 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 88G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 24 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 88G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 24 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 88G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 28 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 96G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 28 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 96G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 28 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 96G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type kvdb --num-threads 32 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 104G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto1 --num-threads 32 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 104G
./out-perf.masstree/benchmarks/dbtest --bench ycsb --db-type ndb-proto2 --num-threads 32 --scale-factor 160000 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 80,0,20,0 --parallel-loading --numa-memory 104G
# Fig 5+6
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 1 --scale-factor 1 --txn-flags 1 --runtime 60 --numa-memory 4G --logfile data.log --assignment 0
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 1 --scale-factor 1 --txn-flags 1 --runtime 60 --numa-memory 4G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 4 --scale-factor 4 --txn-flags 1 --runtime 60 --numa-memory 16G --logfile data.log --assignment 0,1,2,3
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 4 --scale-factor 4 --txn-flags 1 --runtime 60 --numa-memory 16G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 8 --scale-factor 8 --txn-flags 1 --runtime 60 --numa-memory 32G --logfile data.log --assignment 0,1,2,3,4,5,6,7
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 8 --scale-factor 8 --txn-flags 1 --runtime 60 --numa-memory 32G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 12 --scale-factor 12 --txn-flags 1 --runtime 60 --numa-memory 48G --logfile data.log --assignment 0,1,2,3,4,5,6,7,8,9,10,11
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 12 --scale-factor 12 --txn-flags 1 --runtime 60 --numa-memory 48G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 16 --scale-factor 16 --txn-flags 1 --runtime 60 --numa-memory 64G --logfile data.log --assignment 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 16 --scale-factor 16 --txn-flags 1 --runtime 60 --numa-memory 64G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 20 --scale-factor 20 --txn-flags 1 --runtime 60 --numa-memory 80G --logfile data.log --assignment 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 20 --scale-factor 20 --txn-flags 1 --runtime 60 --numa-memory 80G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 24 --scale-factor 24 --txn-flags 1 --runtime 60 --numa-memory 96G --logfile data.log --assignment 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 24 --scale-factor 24 --txn-flags 1 --runtime 60 --numa-memory 96G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --numa-memory 112G --logfile data.log --assignment 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 32 --scale-factor 32 --txn-flags 1 --runtime 60 --numa-memory 128G --logfile data.log --assignment 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 32 --scale-factor 32 --txn-flags 1 --runtime 60 --numa-memory 128G
# Fig 8
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 0 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 1 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 2 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 3 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 4 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 5 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 6 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 7 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 8 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 9 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 10 --numa-memory 112G
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 0 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 1 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 2 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 3 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 4 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 5 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 6 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 7 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 8 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 9 --numa-memory 112G --disable-snapshots
./out-factor-gc.masstree/benchmarks/dbtest --bench tpcc --db-type ndb-proto2 --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --enable-separate-tree-per-partition\ --workload-mix\ 100,0,0,0,0\ --new-order-remote-item-pct\ 10 --numa-memory 112G --disable-snapshots
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 0 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 1 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 2 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 3 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 4 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 5 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 6 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 7 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 8 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 9 --numa-memory 112G
./out-perf.masstree/benchmarks/dbtest --bench tpcc --db-type kvdb-st --num-threads 28 --scale-factor 28 --txn-flags 1 --runtime 60 --bench-opts --workload-mix\ 100,0,0,0,0\ --enable-separate-tree-per-partition\ --enable-partition-locks\ --new-order-remote-item-pct\ 10 --numa-memory 112G