
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8000", "s201:8001", "s301:8002"]
    - ["s102:8100", "s202:8101", "s302:8102"]
    - ["s103:8200", "s203:8201", "s303:8202"]
  client: # each line is a partition
    - ["c01", "c02", "c03"]
    - ["c04", "c05", "c06"]
    - ["c07", "c08", "c09"]
